//
//  LocalPhotosWorker.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

class LocalPhotosWorker {

    func getPhotosByLocation(latitude : Double, longitude : Double) -> [PhotoDTO] {
        let qtPhotos = Int(arc4random_uniform(90))
        
        let filteredLocationPhotos = UaiFotosDataStore.user?.friends?.map({ (friend) -> [(photo: PhotoDTO, friend: UserDTO)]? in
            let locationPhotos = friend.photos?.filter({ $0.location?.latitude == latitude })
            return locationPhotos?.map({ (locPhoto) -> (photo: PhotoDTO, friend: UserDTO) in
                return (locPhoto, friend)
            })
        })
        
        
        return UaiFotosDataStore().generatePhotos(number: qtPhotos)
    }
}
