//
//  LocalPhotosRouter.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LocalPhotosRoutingLogic {
//    func navigateToMainScreen(value: Int)
    
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LocalPhotosDataPassing {
}

class LocalPhotosRouter: NSObject, LocalPhotosRoutingLogic, LocalPhotosDataPassing {
  weak var viewController: LocalPhotosViewController?
  
  var dataStore: LocalPhotosDataStore?
  
//    var value: Int?
//
//    func navigateToMainScreen(value: Int) {
//        self.value = value
//        self.viewController?.performSegue(withIdentifier: "Banana", sender: nil)
//    }
//
//
//    @objc func routeToBananaWithSegue(_ segue: UIStoryboardSegue?) {
//        if let dest = segue?.destination as? UIViewController {
//            dest.xpto = value
//        }
//    }
    
    
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?) {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LocalPhotosViewController, destination: SomewhereViewController) {
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LocalPhotosDataStore, destination: inout SomewhereDataStore) {
  //  destination.name = source.name
  //}
}
