//
//  LocalPhotosInteractor.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol LocalPhotosBusinessLogic {
  func doSomething(request: LocalPhotos.Something.Request)
}

protocol LocalPhotosDataStore {
    var location: MKPointAnnotation? { get set }
}

class LocalPhotosInteractor: LocalPhotosBusinessLogic, LocalPhotosDataStore {

  var location: MKPointAnnotation?
  var presenter: LocalPhotosPresentationLogic?
  var worker: LocalPhotosWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LocalPhotos.Something.Request) {
    worker = LocalPhotosWorker()
    worker?.doSomeWork()
    
    let response = LocalPhotos.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
