//
//  LocalPhotosInteractor.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocalPhotosBusinessLogic {
    func getPhotosByLocation(request: LocalPhotos.PhotosByLocation.Request)
}

protocol LocalPhotosDataStore {

}

class LocalPhotosInteractor: LocalPhotosBusinessLogic, LocalPhotosDataStore {
    
    var presenter: LocalPhotosPresentationLogic?
    var worker: LocalPhotosWorker?

    func getPhotosByLocation(request: LocalPhotos.PhotosByLocation.Request) {
        worker = LocalPhotosWorker()
        let photos = worker?.getPhotosByLocation(latitude: request.latitude, longitude: request.longitude) ?? []
        let response = LocalPhotos.PhotosByLocation.Response(photos: photos)
        presenter?.presentPhotosByLocation(response: response)
    }
}
