//
//  LocalPhotosWorker.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

class LocalPhotosWorker {

    func getPhotosByLocation(latitude : Double, longitude : Double) -> [PhotoDTO] {
        return UaiFotosDataStore().generatePhotos(number: 32)
    }
}
