//
//  SearchWorker.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 12/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
    func searchFriends(searchText: String) -> [UserDTO]? {
        let filteredFriends = UaiFotosDataStore.user?.friends?.filter({ (friend) -> Bool in
            return friend.name!.lowercased().contains(searchText.lowercased())
        })
        return filteredFriends
	}
    
    func getAllFriends() -> [UserDTO]? {
        return UaiFotosDataStore.user?.friends
    }
}
