//
//  SearchPresenter.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 12/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentFriends(response: Search.Friends.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: presentFriends
    func presentFriends(response: Search.Friends.Response) {
        var displayedFriends: [Search.Friends.ViewModel.DisplayFriend] = []
        if let friends = response.filteredFriends {
            for friend in friends {
                let displayedFriend = Search.Friends.ViewModel.DisplayFriend(name: friend.name!, avatarUrl: friend.avatarUrl, title: friend.title!)
                
                displayedFriends.append(displayedFriend)
            }
        }
        
        let viewModel = Search.Friends.ViewModel(displayedFriends: displayedFriends)
        viewController?.displayFriends(viewModel: viewModel)
    }
}
