//
//  SearchInteractor.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 12/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func filterFriendsForSearchText(request: Search.Friends.Request)
    func getAllFriends()
}

protocol SearchDataStore {
    var friends: [UserDTO]? { get }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    
    var friends: [UserDTO]?
    
    func getAllFriends() {
        self.worker = SearchWorker()
        self.friends = self.worker?.getAllFriends()
        
        let response = Search.Friends.Response(filteredFriends: self.friends)
        self.presenter?.presentFriends(response: response)
    }
    
    func filterFriendsForSearchText(request: Search.Friends.Request) {
        worker = SearchWorker()
        self.friends = worker?.searchFriends(searchText: request.searchText)
        
        let response = Search.Friends.Response(filteredFriends: self.friends)
        presenter?.presentFriends(response: response)
    }
}
