//
//  SearchRouter.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 12/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
  func routeToProfile(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing {
  var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
  weak var viewController: SearchViewController?
  var dataStore: SearchDataStore?
  
  // MARK: Routing
  
  func routeToProfile(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = segue.destination as! ProfileViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToProfile(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Profile", bundle: nil)
      let destinationVC = storyboard.instantiateInitialViewController() as! ProfileViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToProfile(source: dataStore!, destination: &destinationDS)
      navigateToProfile(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToProfile(source: SearchViewController, destination: ProfileViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToProfile(source: SearchDataStore, destination: inout ProfileDataStore) {
    let selectedRow = self.viewController?.tableView.indexPathForSelectedRow?.row
    destination.user = source.friends?[selectedRow!]
  }
}
