//
//  ProfileInteractor.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func getUser()
}

protocol ProfileDataStore {
    var user: UserDTO? { get }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    
    var user: UserDTO?
    
    // MARK: Do something
    
    func getUser() {
        worker = ProfileWorker()
        self.user = worker?.getLoggedUser()
        
        let response = Profile.User.Response(loggedUser: self.user)
        presenter?.presentUser(response: response)
    }
}
