//
//  ProfileModels.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
  // MARK: Use cases
  
  enum User {
    struct Request {
    }
    
    struct Response {
        var loggedUser: UserDTO?
    }
    
    struct ViewModel {
        struct DisplayUser {
            var name: String
            var avatar: URL
            var publications: String
            var followers: String
            var following: String
            var bio: NSAttributedString
            var photos: [URL]
        }
        var displayUser: DisplayUser?
    }
  }
}
