//
//  ProfileRouter.swift
//  Uai Fotos
//
//  Created by Elifazio Bernardes da Silva on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProfileRoutingLogic {
    func routeToActivityDetail(segue: UIStoryboardSegue?)
}

protocol ProfileDataPassing {
    var dataStore: ProfileDataStore? { get }
}

class ProfileRouter: NSObject, ProfileRoutingLogic, ProfileDataPassing {
    weak var viewController: ProfileViewController?
    var dataStore: ProfileDataStore?
    
    // MARK: Routing
    
    func routeToActivityDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ActivityDetailViewController
            //var destinationDS = destinationVC.router!.dataStore!
            passDataToActivityDetail(source: dataStore!, destination: destinationVC)
        } else {
            let storyboard = UIStoryboard(name: "Heart", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "activityDetailViewController") as! ActivityDetailViewController
            //var destinationDS = destinationVC.router!.dataStore!
            passDataToActivityDetail(source: dataStore!, destination: destinationVC)
            navigateToActivityDetail(source: self.viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    func navigateToActivityDetail(source: ProfileViewController, destination: ActivityDetailViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToActivityDetail(source: ProfileDataStore, destination: ActivityDetailViewController) {
        if let selectedRow = self.viewController?.collectionView.indexPathsForSelectedItems?.first?.row {
            let photo = source.user?.photos?[selectedRow]
            destination.activityDetail = (photo!, source.user!)
        }
    }
}
